import "./globals.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

const fontSans = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full font-sans">
      <body className={`${fontSans.variable} h-full font-sans`}>
        {children}
      </body>
    </html>
  );
}
